### ISSUE TITLE
Contributing Guidelines - Requirement 3: Guidelines for Filing an Issue

### ISSUE THREAD

**Issue by HectorJBastidasG** [RentadroneCL/Web-API#20]
Rubric Open Source (Justin Flory)

*EVALUATION*: Yellow
*SUBJECT*: Contributing Guidelines - Requirement 3: Guidelines for Filing an Issue
*DETAIL*: Guidelines may not fit many issues being filed but overall provide a unitary theme to issues submitted.
*POSSIBLE SOLUTION*: Include step-by-step instructions on how to open an issue

**Comment by afariasfermin** [comment]
addressed in #19
