### ISSUE TITLE
Developer Documentation - Requirement 4: Project Hierarchy Explaination

### ISSUE THREAD

**Issue by HectorJBastidasG** [RentadroneCL/Web-API#21]
Rubric Open Source (Justin Flory)

*EVALUATION*: Yellow
*SUBJECT*: Developer Documentation - Requirement 4: Project Hierarchy Explaination
*DETAIL*: The organization of the repos is explained, without visuals. Each component may or may not get a proper explaination.
*POSSIBLE SOLUTION*: Include visuals of the repositories and own explanations for each repo for dummies

**Comment by afariasfermin** [comment]
Addressed in #25
